### ISSUE TITLE
look into getting rid of CloseApplication event/delegate

### ISSUE THREAD

**Issue by stephenwade** [Deadpikle/NetSparkle#18]
Instead of hooking into these events to handle closing the app, the app should either hook into AboutToExitForInstallerRun, or properly handle the [Application.Exit] event or the [Form.FormClosing] event as if otherwise closed (by closing the last window or by a system shutdown).

[Application.Exit]: https://msdn.microsoft.com/en-us/library/system.windows.application.exit.aspx
[Form.FormClosing]: https://msdn.microsoft.com/en-us/library/system.windows.forms.form.formclosing(v=vs.110).aspx

**Comment by Deadpikle** [comment]
Deciding to keep `CloseApplication` for now so that users can have the most customization possible. `AboutToExitForInstallerRun` is a "pre-closing" event and shouldn't actually kill things yet, so we can't kill everything there. I'd rather they handle things through NetSparkle instead with the whole custom UI thing (since technically they could use this without WPF or WinForms!), so I'm keeping it.
