### ISSUE TITLE
NuGet package available ?

### ISSUE THREAD

**Issue by delfuria** [Deadpikle/NetSparkle#27]
Hi, is there a nuget package of this repo ?
Thanks

**Comment by Deadpikle** [comment]
Hi @delfuria! There isn't this moment, but I can put one together! I'll reply again and close this issue when it's ready.

**Comment by delfuria** [comment]
Thanks for the reply.
I found the "your" version of NetSparkle is a great step forward over the original version, and i think that everyone that currently use the "old" version will use yours.

**Comment by Deadpikle** [comment]
@delfuria Does https://www.nuget.org/packages/com.pikleproductions.netsparkle/ and/or https://www.nuget.org/packages/com.pikleproductions.netsparkle.tools/ work for you?

I've contacted the current NuGet NetSparkle owners to see if I can have access to that package so we can get rid of the NetSparkle.New name. I should probably bump the version # to 1.2 or similar, too, so that people online aren't confused. More to do later, so I'll keep this open.

**Comment by Deadpikle** [comment]
@delfuria Does https://www.nuget.org/packages/NetSparkle.New/ and/or https://www.nuget.org/packages/NetSparkle.New.Tools/ work for you? 

Note that the published version is 0.10.0, so you may have to make a few adjustments if you were building with 0.9.x before (`master` branch). `CHANGELOG.md` should let you know what you need to know to update.

I've contacted the current NuGet NetSparkle owners to see if I can have access to that package so we can get rid of the NetSparkle.New name. I should probably bump the version # to 1.2 or similar, too, so that people online aren't confused -- although with all the changes, 2.0 might be more appropriate. I'll think about it.

**Comment by delfuria** [comment]
Thanks a lot !!!
