### ISSUE TITLE
I want to update some dynamic link libraries. What should I do?

### ISSUE THREAD

**Issue by MarshalT** [Deadpikle/NetSparkle#54]
I want to update some dynamic link libraries. What should I do?

**Comment by Deadpikle** [comment]
Hi @MarshalT !

You have a few options depending on how your software works and how it uses the DLLs that you want to update. I'm assuming here you have a .zip of DLL updates or something similar. NetSparkle itself doesn't enforce what it downloads, but it does assume the downloaded item is an `exe`, `msi`, or `msp` **unless** you override `NetSparkle.RunDownloadedInstaller` OR `NetSparkle.GetInstallerCommand`. Are you wanting to run both software updates and DLL updates or keep them separate? Can you explain your desired update process a little more?

Here's some notes off the top of my head without knowing more about what you want:

* Nothing stopping you from creating a small installer with something like InnoSetup that is run to extract the DLLs to the appropriate place just like a "normal" software update.
* You could override `NetSparkle.RunDownloadedInstaller` to extract the DLLs to the applicable installation directory of your software. Remember that this might need admin rights. When this function runs, though, your software is still running and will be until you close it. From your overridden function, you could create a .bat file and run it after your software closes. It could, for example, extract the DLLs or do the other work you need. This saves you from having to create an installer. Since this function can be overridden, you can pretty much explicitly control the install process on your own -- you could even make it so that it installs without your software closing!
* Don't forget you can set `NetSparkle.SilentMode` to adjust how much the user is told about what is happening
* Don't forget that if you try to overwrite a DLL that your software is using, your mileage may vary on if this is successful or not 😅 

Let me know if that helps or if you need more information. Please share more about your desired update process if you want more specific suggestions.

**Comment by MarshalT** [comment]
@ Hi Deadpikle!
Thank you for your answer.I've found a simpler update component.
