### ISSUE TITLE
Be able to override the registry key used to store the Configuration

### ISSUE THREAD

**Issue by Mostlypyjamas** [Deadpikle/NetSparkle#67]
I'm really loving Netsparkle I have to say - really great work.  One thing that we've spotted coming from Winsparkle over to Netsparkle is the ability to override the registry key used to store the config.

With Winsparkle you can call win_sparkle_set_registry_path  and having a property we can use or a method to call on Netsparkle would be great just so we can keep the reg key info for all our different applications alongside our usual user data

Just an idea, keep up the good work!

**Comment by Deadpikle** [comment]
@Mostlypyjamas 

Good suggestion! You can now do this on the `develop` branch. (Let me know if you need this on NuGet so I can `cherry-pick` to `master`.)

To set this, just create a subclass of `RegistryConfiguration` and override `BuildRegistryPath()`, which returns a `String`. Then set the `Configuration` parameter of your `NetSparkle` object. I decided not to add another param to `NetSparkle` for this due to the already-large number of params there already.

Thanks! Thanks also for the encouragement -- it's, well, encouraging!

**Comment by Mostlypyjamas** [comment]
That's great yes - if you were able to cherry pick that across to the nuget as 0.17.1 or similar that would be great :)  Equally, it's no problem if you want to hold off for a later roll up anyway.

**Comment by Deadpikle** [comment]
`0.18.0` with just this one change to that class is now processing on NuGet and should be available shortly!

**Comment by Mostlypyjamas** [comment]
That's fantastic and works brilliantly - thank you!
